const { chromium } = require('/opt/node22/lib/node_modules/playwright');
(async () => {
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-proxy-server','--disable-dev-shm-usage','--disable-gpu','--no-sandbox'] });
  const p = await b.newPage(); p.on('pageerror', e=>console.log('PAGEERROR',e.message));
  const KEY='nand2tetris-lomda-v12', URL='http://localhost:8272/index.html';
  const seed = { screen:'story', chapterId:'chapter-10', sceneId:'flipflop', panelIndex:7, started:true, maxChapterReached:20, settings:{pace:'all'}, completedTasks:[] };
  await p.goto(URL,{waitUntil:'commit'});
  await p.evaluate(([k,v])=>localStorage.setItem(k,JSON.stringify(v)),[KEY,seed]);
  await p.reload({waitUntil:'commit'}); await p.waitForTimeout(900);
  const clk = async (s)=>{const e=await p.$(s); await e.click({force:true}); await p.waitForTimeout(200);};
  await clk("[data-action='memory-tasks-note']");
  await clk("[data-action='memory-note-task'][data-task-id='Register4']");
  await p.waitForTimeout(500);
  const bodyText = await p.evaluate(()=>document.body.innerText);
  console.log('has requirements text (Register4/פליפ-פלופ):', /פליפ-פלופ/.test(bodyText) && /Register4/.test(bodyText));
  console.log('requirements excerpt:', (bodyText.match(/ל-Register4[^]{0,80}/)||[''])[0].replace(/\s+/g,' '));
  const checkBtn = await p.$("[data-action='check-not-task']");
  const hintBtn = await p.$("[data-action='hint-open']");
  console.log('check button:', !!checkBtn, '| hint button:', !!hintBtn);
  await b.close();
})().catch(e=>{console.error('ERR',e);process.exit(1);});
